import { CompletionModels } from '../types/completionModels'
import {
  openAIChatCompletionModelsArray,
  openAITextCompletionInstructModelsArray,
  openAIVisionModelsArray,
  huggingFaceModelsWithPromptFormattingArray,
  ollamaModelsArray,
  ollamaVisionModelsArray,
  vertexAIGoogleModelsArray,
  palmModelsArray,
  googleAIStudioModelsArray,
  mistralAIModelsArray,
  anthropicModelsArray,
  sageMakerModelsArray,
  bedrockModelsArray,
  perplexityAIModelsArray,
  vllmModelsArray,
  xinferenceModelsArray,
  cloudflareWorkersAIModelsArray,
  ai21ModelsArray,
  nlpCloudModelsArray,
  deepInfraChatModelsArray,
  togetherAIModelsArray,
  baseTenModelsArray,
  petalsModelsArray,
  voyageAIModelsArray,
  alephAlphaModelsArray,
} from './completionModelArrays'

export const allCompletionModels: CompletionModels[] = [
  ...openAIChatCompletionModelsArray,
  ...openAITextCompletionInstructModelsArray,
  ...openAIVisionModelsArray,
  ...huggingFaceModelsWithPromptFormattingArray,
  ...ollamaModelsArray,
  ...ollamaVisionModelsArray,
  ...vertexAIGoogleModelsArray,
  ...palmModelsArray,
  ...googleAIStudioModelsArray,
  ...mistralAIModelsArray,
  ...anthropicModelsArray,
  ...sageMakerModelsArray,
  ...bedrockModelsArray,
  ...perplexityAIModelsArray,
  ...vllmModelsArray,
  ...xinferenceModelsArray,
  ...cloudflareWorkersAIModelsArray,
  ...ai21ModelsArray,
  ...nlpCloudModelsArray,
  ...deepInfraChatModelsArray,
  ...togetherAIModelsArray,
  ...baseTenModelsArray,
  ...petalsModelsArray,
  ...voyageAIModelsArray,
  ...alephAlphaModelsArray,
]
