// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  panel: string
  round: string
  rounder: string
  roundest: string
  shadow: string
  square: string
  unpadded: string
}
export const cssExports: CssExports
export default cssExports
