// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  message: string
  flexCenterBtn: string
  flexCenterStart: string
  inputContainer: string
  typeInfo: string
  inputNode: string
}
export const cssExports: CssExports
export default cssExports
