// DOCUMENTED
/**
 * @fileoverview A module that manages status bar state using Redux Toolkit.
 * @package
 */

import { createSlice } from '@reduxjs/toolkit'

/** Interface for the status bar state. */
export interface StatusBarState {
  syncing: boolean
}

/** The initial state for status bar. */
const initialState: StatusBarState = {
  syncing: false,
}

/**
 * A Slice that creates reducers and actions for status bar.
 * @param name - The name of the slice.
 * @param initialState - The initial state of the slice.
 * @param reducers - Reducers that modify the state, generated by createSlice.
 */
export const statusBarSlice = createSlice({
  name: 'statusBar',
  initialState,
  reducers: {
    setSyncing: (state, action) => {
      state.syncing = action.payload
    },
  },
})

/** Actions generated from the status bar slice. */
export const { setSyncing } = statusBarSlice.actions

/** The status bar reducer generated by the slice. */
export default statusBarSlice.reducer
