// DOCUMENTED
/**
 * @fileoverview A module that manages user preferences using Redux Toolkit.
 * @package
 */

import { createSlice } from '@reduxjs/toolkit'

export interface Tab {
  id: string
  title: string
  params: Record<string, unknown>
}

/** Interface for the tab layout state. */
export interface TabLayoutState {
  currentTab: Tab | null
}

/** The initial state for tab layouts. */
const initialState: TabLayoutState = {
  currentTab: null,
}

/**
 * A Slice that creates reducers and actions for tab layout.
 * @param name - The name of the slice.
 * @param initialState - The initial state of the slice.
 * @param reducers - Reducers that modify the state, generated by createSlice.
 */
export const tabLayoutSlice = createSlice({
  name: 'tabLayout',
  initialState,
  reducers: {
    /**
     * Toggles the auto-save tab layout, modifying the state accordingly.
     * @param state - The current state of the tab layout.
     */
    setCurrentTab: (state, action) => {
      state.currentTab = action.payload
    },
  },
})

/** Actions generated from the tab layout slice. */
export const { setCurrentTab } = tabLayoutSlice.actions

/** The tab layout reducer generated by the slice. */
export default tabLayoutSlice.reducer
