// DOCUMENTED
/**
 * @fileoverview A module that manages user preferences using Redux Toolkit.
 * @package
 */

import { createSlice } from '@reduxjs/toolkit'

export interface Panel {
  id: string
  title: string
}

/** Interface for the preference state. */
export interface TabLayoutState {
  currentTab: Panel | null
}

/** The initial state for preferences. */
const initialState: TabLayoutState = {
  currentTab: null,
}

/**
 * A Slice that creates reducers and actions for preferences.
 * @param name - The name of the slice.
 * @param initialState - The initial state of the slice.
 * @param reducers - Reducers that modify the state, generated by createSlice.
 */
export const tabLayoutSlice = createSlice({
  name: 'tabLayout',
  initialState,
  reducers: {
    /**
     * Toggles the auto-save preference, modifying the state accordingly.
     * @param state - The current state of the preferences.
     */
    setCurrentTab: (state, action) => {
      state.currentTab = action.payload
    },
  },
})

/** Actions generated from the preference slice. */
export const { setCurrentTab } = tabLayoutSlice.actions

/** The preference reducer generated by the slice. */
export default tabLayoutSlice.reducer
