// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  active: string
  'create-spell-tab': string
  inactive: string
  'tabbar-section': string
  'tabbar-tab': string
  'tabbar-user': string
  'th-tabbar': string
}
export const cssExports: CssExports
export default cssExports
