# local postgres database if you need it
version: '3.4'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  db:
    restart: always
    image: postgresai/extended-postgres:15-0.2.0
    hostname: magick_db
    environment:
      POSTGRES_DB: magick
      POSTGRES_USER: magick
      POSTGRES_PASSWORD: magick_default_pw
    ports:
      - '5432:5432'
volumes:
  cache:
    driver: local
