version: '3.4'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  postgres:
    restart: always
    image: ankane/pgvector:v0.4.1
    hostname: magick_db
    environment:
      POSTGRES_DB: magick
      POSTGRES_USER: magick
      POSTGRES_PASSWORD: magick_default_pw    
    ports:
      - '5432:5432'
volumes:
  cache:
    driver: local
