version: '3.4'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  postgres:
    restart: always
    image: ankane/pgvector:v0.4.1
    hostname: magick_db
    environment:
      POSTGRES_DB: magick
      POSTGRES_USER: magick
      POSTGRES_PASSWORD: magick_default_pw    
    ports:
      - '5432:5432'
  ninja:
    container_name: s3-ninja
    image: scireum/s3-ninja
    restart: always
    ports:
      - 9444:9000
    volumes:
      - ./data:/opt/s3ninja/data
volumes:
  cache:
    driver: local
