[tool.poetry]
name = "magick"
version = "0.1.0"
description = "More than just a rabbit in a hat"
authors = ["Your Name <you@example.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
litellm = "^1.15.1"
setuptools = "^69.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
