// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'folder-arrow': string
  'list-item': string
  'menu-bar': string
  'menu-bar-item': string
  'menu-panel': string
  'preference-active': string
  'preference-notActive': string
}
export const cssExports: CssExports
export default cssExports
