apiVersion: apps/v1
kind: Deployment
metadata:
  name: magick-client
spec:
  selector:
    matchLabels:
      app: magick-client
  replicas: 1
  template:
    metadata:
      labels:
        app: magick-client
    spec:
      tolerations:
        - key: "appservicesonly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: server
          image: 389959444765.dkr.ecr.us-east-1.amazonaws.com/magick-client:latest
          args: ["npm run docker"]
          stdin: true
          tty: true
          ports:
            - containerPort: 3003
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: USE_SSL
              value: "false"
            - name: URL_SCHEME
              value: "http"
            - name: REACT_APP_OAUTH_CLIENT_ID
              value: "a6b51c87-7565-42ab-a4b0-38a07f3b6c56"
            - name: REACT_APP_SPEECH_SERVER_URL
              value: "https://magick-server.projectlazarus.ai:65532"
            - name: REACT_APP_SEARCH_SERVER_URL
              value: "https://magick-server.projectlazarus.ai:65531"
            - name: REACT_APP_API_URL
              value: "https://magick-server.projectlazarus.ai"
            - name: API_URL
              value: "https://magick-server.projectlazarus.ai"
            - name: REACT_APP_FEATHERS
              value: "false"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: magick-client
spec:
  selector:
    app: magick-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: magick-client-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:389959444765:certificate/bdd1359a-55a4-47f0-bce3-946bc57a0031

spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: magick-client
                port:
                  number: 80
