apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-spellcheck
spec:
  selector:
    matchLabels:
      app: text-spellcheck
  replicas: 1
  template:
    metadata:
      labels:
        app: text-spellcheck
    spec:
      containers:
        - name: text-spellcheck
          image: semitechnologies/text-spellcheck-model:pyspellchecker-en
          stdin: true
          tty: true
          ports:
            - containerPort: 8888
              protocol: TCP
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: text-spellcheck
spec:
  selector:
    app: text-spellcheck
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
