apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoth-server
spec:
  selector:
    matchLabels:
      app: thoth-server
  replicas: 1
  template:
    metadata:
      labels:
        app: thoth-server
    spec:
      tolerations:
        - key: "appservicesonly"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: server
          image: 389959444765.dkr.ecr.us-east-1.amazonaws.com/thoth-server:latest
          workingDir: /app/packages/server
          args:
            [
              'concurrently "nodemon src/server.ts" "yarn run speech" "sleep 1 && yarn run search" "sleep 2 && yarn run entity-server"',
            ]
          stdin: true
          tty: true
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: USE_LATITUDE_API
              value: "false"
            - name: API_URL
              value: http://localhost:8001
            - name: EXTEND_ESLINT
              value: "true"
            - name: PORT
              value: "8001"
            - name: AGENT_RUNNER_PORT
              value: "8003"
            - name: CREATOR_TOOLS_DB_URL
              value:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: nothingprojects-lazarus.cbfjobrijahm.us-east-1.rds.amazonaws.com
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: lazarus-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: "5432"
            - name: PGSSL
              value: "false"
            - name: REFRESH_DB
              value: "false"
            - name: CORS_PORT
              value: "65526"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: google_credentials.json
            - name: SPEECH_SERVER_PORT
              value: "65532"
            - name: ENABLE_SPEECH_SERVER
              value: "true"
            - name: SEARCH_CORPUS_PORT
              value: "65531"
            - name: ENABLE_SEARCH_CORPUS
              value: "true"
            - name: UBER_DUCK_KEY
              value:
            - name: UBER_DUCK_SECRET_KEY
              value:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: servicesecrets
                  key: OPENAI_API_KEY
            - name: HF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: servicesecrets
                  key: HF_API_KEY
              value:
            - name: USSSL_SPEECH
              value: "false"
            - name: FILE_SERVER_PORT
              value: "65530"
            - name: FILE_SERVER_URL
              value: http://localhost:65530
            - name: USESSL
              value: "false"
            - name: WITAI_KEY
              value:
            - name: RUN_PYTHON_SERVER
              value: "false"
            - name: PYTHON_SERVER_URL
              value: http://localhost:7777
            - name: WEAVIATE_CLIENT_SCHEME
              value: http
            - name: WEAVIATE_CLIENT_HOST
              value: waviate:8080
            - name: WEAVIATE_IMPORT_DATA
              value: "false"
            - name: CLASSIFIER_IMPORT_DATA
              value: "false"
            - name: REDIS_URL
              value: redis://redis:6379
            - name: ENTITY_WEBSERVER_PORT_RANGE
              value: 65510-65529
            - name: ENTITY_HOSTNAME
              value: thoth-runner
            - name: EMAIL_HOST
              value: smtp.gmail.com
            - name: EMAIL_PORT
              value: "587"
            - name: EMAIL_SECURE
              value: "false"
            - name: EMAIL_USER
              value:
            - name: EMAIL_PASSWORD
              value:
            - name: TIKTALKNET_URL
              value: http://0.0.0.0:8050/tts
            - name: REACT_APP_CORS_URL
              value: https://localhost:65526
            - name: REACT_APP_SEARCH_SERVER_URL
              value: http://localhost:65531
            - name: AUTHENTICATION
              value: "false"
            - name: AUTHENTICATION_SECRET_KEY
              value: thoth
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: thoth-server
spec:
  selector:
    app: thoth-server
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8001
    - protocol: TCP
      port: 65532
      name: speech
      targetPort: 65532
    - protocol: TCP
      port: 65531
      name: search
      targetPort: 65531

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thoth-server-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:389959444765:certificate/bdd1359a-55a4-47f0-bce3-946bc57a0031

spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: thoth-server
                port:
                  number: 80
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: thoth-server
                port:
                  number: 65532
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: thoth-server
                port:
                  number: 65531
