export const enkiTaskTest = {
  name: 'essential copper',
  graph: {
    id: 'demo@0.1.0',
    nodes: {
      78: {
        id: 78,
        data: {
          socketKey: '1c15de53-4c00-4ef7-a554-4c9dd7f3f487',
          dataControls: {
            name: {
              expanded: true,
            },
          },
          name: 'trigger',
        },
        inputs: {},
        outputs: {
          trigger: {
            connections: [
              {
                node: 80,
                input: 'trigger',
                data: {
                  pins: [],
                },
              },
            ],
          },
        },
        position: [-782.8281555175781, -365.20770263671875],
        name: 'Module Trigger In',
      },
      79: {
        id: 79,
        data: {
          socketKey: '212bd2fd-a1fb-428c-ac81-1da928380106',
          dataControls: {
            name: {
              expanded: true,
            },
          },
          name: 'item',
        },
        inputs: {},
        outputs: {
          output: {
            connections: [
              {
                node: 80,
                input: 'input1',
                data: {
                  pins: [],
                },
              },
            ],
          },
        },
        position: [-781.8570861816406, -231.09637451171875],
        name: 'Module Input',
      },
      80: {
        id: 80,
        data: {
          dataControls: {
            'throughputs-80': {
              expanded: true,
            },
          },
          'throughputs-80': {
            inputs: [
              {
                name: 'Trigger',
                socketKey: 'trigger',
                socketType: 'triggerSocket',
                taskType: 'option',
              },
              {
                name: 'input1',
                socketKey: 'input1',
                socketType: 'stringSocket',
                taskType: 'output',
              },
            ],
            outputs: [
              {
                name: 'Trigger',
                socketKey: 'trigger',
                socketType: 'triggerSocket',
                taskType: 'option',
              },
              {
                name: 'output1',
                socketKey: 'output1',
                socketType: 'stringSocket',
                taskType: 'output',
              },
            ],
            activeTask: {
              taskName: 'Crafting',
              task: {
                id: '235',
                name: 'Crafting',
                numInputs: 1,
                numOutputs: 1,
                unstuffedParentId: null,
                createdAt: '2021-06-01T19:28:42.932Z',
                updatedAt: '2021-06-01T19:28:42.932Z',
                deletedAt: null,
              },
              data: [
                {
                  id: '395',
                  fewshotTaskId: '235',
                  inputs: ['trap'],
                  outputs: ['wood(3), lashing(2)'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:43.509Z',
                  updatedAt: '2021-06-01T19:28:43.509Z',
                  deletedAt: null,
                },
                {
                  id: '402',
                  fewshotTaskId: '235',
                  inputs: ['wooden spear'],
                  outputs: ['wood(3)'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:44.893Z',
                  updatedAt: '2021-06-01T19:28:44.893Z',
                  deletedAt: null,
                },
                {
                  id: '396',
                  fewshotTaskId: '235',
                  inputs: ['shelter'],
                  outputs: ['wood(4), lashing(2)\n'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:43.682Z',
                  updatedAt: '2021-06-01T19:28:43.682Z',
                  deletedAt: null,
                },
                {
                  id: '403',
                  fewshotTaskId: '235',
                  inputs: ['trap'],
                  outputs: ['wood(3), lashing(2)'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:44.905Z',
                  updatedAt: '2021-06-01T19:28:44.905Z',
                  deletedAt: null,
                },
                {
                  id: '414',
                  fewshotTaskId: '235',
                  inputs: ['shotgun'],
                  outputs: ['shotgun barrel(1), shotgun parts(3), ammo(20)'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:29:52.843Z',
                  updatedAt: '2021-06-01T19:29:52.843Z',
                  deletedAt: null,
                },
                {
                  id: '397',
                  fewshotTaskId: '235',
                  inputs: ['plane parts'],
                  outputs: ['uncraftable'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:43.685Z',
                  updatedAt: '2021-06-01T19:28:43.685Z',
                  deletedAt: null,
                },
                {
                  id: '404',
                  fewshotTaskId: '235',
                  inputs: ['plane parts'],
                  outputs: ['uncraftable'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:44.915Z',
                  updatedAt: '2021-06-01T19:28:44.915Z',
                  deletedAt: null,
                },
                {
                  id: '398',
                  fewshotTaskId: '235',
                  inputs: ['jeep'],
                  outputs: ['jeep frame(1), jeep parts(3), fuel(20)\n'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:43.946Z',
                  updatedAt: '2021-06-01T19:28:43.946Z',
                  deletedAt: null,
                },
                {
                  id: '410',
                  fewshotTaskId: '235',
                  inputs: ['jeep'],
                  outputs: ['jeep frame(1), jeep parts(3), fuel(20)\n'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:28:45.197Z',
                  updatedAt: '2021-06-01T19:28:45.197Z',
                  deletedAt: null,
                },
                {
                  id: '412',
                  fewshotTaskId: '235',
                  inputs: ['cloth dress'],
                  outputs: ['cloth(3)'],
                  creator: '23505660',
                  provenance: null,
                  tags: null,
                  createdAt: '2021-06-01T19:29:52.804Z',
                  updatedAt: '2021-06-01T19:29:52.804Z',
                  deletedAt: null,
                },
              ],
              serialization: {
                id: '169',
                fewshotTaskId: '235',
                name: 'default',
                isPreferred: true,
                introduction:
                  'Given an item decide what it takes to craft it\n\n',
                beforeEachInput: ['Item: '],
                inBetween: '\nRequired: ',
                beforeEachOutput: [''],
                atTheEnd: '\n\nNEXT\n\n',
                createdAt: '2021-06-01T19:28:43.359Z',
                updatedAt: '2021-06-01T19:29:31.094Z',
                deletedAt: null,
              },
            },
          },
          outputs: [
            {
              name: 'Trigger',
              socketKey: 'trigger',
              socketType: 'triggerSocket',
              taskType: 'option',
            },
            {
              name: 'output1',
              socketKey: 'output1',
              socketType: 'stringSocket',
              taskType: 'output',
            },
          ],
          inputs: [
            {
              name: 'Trigger',
              socketKey: 'trigger',
              socketType: 'triggerSocket',
              taskType: 'option',
            },
            {
              name: 'input1',
              socketKey: 'input1',
              socketType: 'stringSocket',
              taskType: 'output',
            },
          ],
          name: 'Crafting',
          activetask: {
            taskName: 'Crafting',
            task: {
              id: '235',
              name: 'Crafting',
              numInputs: 1,
              numOutputs: 1,
              unstuffedParentId: null,
              createdAt: '2021-06-01T19:28:42.932Z',
              updatedAt: '2021-06-01T19:28:42.932Z',
              deletedAt: null,
            },
            data: [
              {
                id: '395',
                fewshotTaskId: '235',
                inputs: ['trap'],
                outputs: ['wood(3), lashing(2)'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:43.509Z',
                updatedAt: '2021-06-01T19:28:43.509Z',
                deletedAt: null,
              },
              {
                id: '402',
                fewshotTaskId: '235',
                inputs: ['wooden spear'],
                outputs: ['wood(3)'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:44.893Z',
                updatedAt: '2021-06-01T19:28:44.893Z',
                deletedAt: null,
              },
              {
                id: '396',
                fewshotTaskId: '235',
                inputs: ['shelter'],
                outputs: ['wood(4), lashing(2)\n'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:43.682Z',
                updatedAt: '2021-06-01T19:28:43.682Z',
                deletedAt: null,
              },
              {
                id: '403',
                fewshotTaskId: '235',
                inputs: ['trap'],
                outputs: ['wood(3), lashing(2)'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:44.905Z',
                updatedAt: '2021-06-01T19:28:44.905Z',
                deletedAt: null,
              },
              {
                id: '414',
                fewshotTaskId: '235',
                inputs: ['shotgun'],
                outputs: ['shotgun barrel(1), shotgun parts(3), ammo(20)'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:29:52.843Z',
                updatedAt: '2021-06-01T19:29:52.843Z',
                deletedAt: null,
              },
              {
                id: '397',
                fewshotTaskId: '235',
                inputs: ['plane parts'],
                outputs: ['uncraftable'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:43.685Z',
                updatedAt: '2021-06-01T19:28:43.685Z',
                deletedAt: null,
              },
              {
                id: '404',
                fewshotTaskId: '235',
                inputs: ['plane parts'],
                outputs: ['uncraftable'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:44.915Z',
                updatedAt: '2021-06-01T19:28:44.915Z',
                deletedAt: null,
              },
              {
                id: '398',
                fewshotTaskId: '235',
                inputs: ['jeep'],
                outputs: ['jeep frame(1), jeep parts(3), fuel(20)\n'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:43.946Z',
                updatedAt: '2021-06-01T19:28:43.946Z',
                deletedAt: null,
              },
              {
                id: '410',
                fewshotTaskId: '235',
                inputs: ['jeep'],
                outputs: ['jeep frame(1), jeep parts(3), fuel(20)\n'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:28:45.197Z',
                updatedAt: '2021-06-01T19:28:45.197Z',
                deletedAt: null,
              },
              {
                id: '412',
                fewshotTaskId: '235',
                inputs: ['cloth dress'],
                outputs: ['cloth(3)'],
                creator: '23505660',
                provenance: null,
                tags: null,
                createdAt: '2021-06-01T19:29:52.804Z',
                updatedAt: '2021-06-01T19:29:52.804Z',
                deletedAt: null,
              },
            ],
            serialization: {
              id: '169',
              fewshotTaskId: '235',
              name: 'default',
              isPreferred: true,
              introduction:
                'Given an item decide what it takes to craft it\n\n',
              beforeEachInput: ['Item: '],
              inBetween: '\nRequired: ',
              beforeEachOutput: [''],
              atTheEnd: '\n\nNEXT\n\n',
              createdAt: '2021-06-01T19:28:43.359Z',
              updatedAt: '2021-06-01T19:29:31.094Z',
              deletedAt: null,
            },
          },
        },
        inputs: {
          trigger: {
            connections: [
              {
                node: 78,
                output: 'trigger',
                data: {
                  pins: [],
                },
              },
            ],
          },
          input1: {
            connections: [
              {
                node: 79,
                output: 'output',
                data: {
                  pins: [],
                },
              },
            ],
          },
        },
        outputs: {
          trigger: {
            connections: [
              {
                node: 81,
                input: 'trigger',
                data: {
                  pins: [],
                },
              },
            ],
          },
          output1: {
            connections: [
              {
                node: 81,
                input: 'input',
                data: {
                  pins: [],
                },
              },
            ],
          },
        },
        position: [-388.7842881066687, -285.2609592400301],
        name: 'Enki Task',
      },
      81: {
        id: 81,
        data: {
          socketKey: 'bdab0eb0-11ad-49ac-9cea-06cf2d9fdcdf',
        },
        inputs: {
          input: {
            connections: [
              {
                node: 80,
                output: 'output1',
                data: {
                  pins: [],
                },
              },
            ],
          },
          trigger: {
            connections: [
              {
                node: 80,
                output: 'trigger',
                data: {
                  pins: [],
                },
              },
            ],
          },
        },
        outputs: {},
        position: [-29.58056640625, -288.65252685546875],
        name: 'Module Output',
      },
    },
  },
  gameState: {},
  createdAt: 1633728021053,
  updatedAt: 1633728160269,
  modules: [],
}
