// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bottom-container': string;
  'code-editor': string;
  'form-text-area': string;
  'node-bottom-container': string;
  'node-grid': string;
  'node-grid-item': string;
  'node-title': string;
  'playtest-input': string;
  'playtest-output': string;
  'tab': string;
  'tab-page': string;
  'tabs': string;
  'th-sidepanel': string;
}
export const cssExports: CssExports;
export default cssExports;
