// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  chip: string
  'no-events': string
}
export const cssExports: CssExports
export default cssExports
