// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bordered': string;
  'darkened': string;
  'darker': string;
  'grid': string;
  'lock-bar': string;
  'unpadded': string;
  'window': string;
  'window-layout': string;
  'window-toolbar': string;
}
export const cssExports: CssExports;
export default cssExports;
