// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown-indicator': string;
  'group-header': string;
  'select-dropdown-container': string;
}
export const cssExports: CssExports;
export default cssExports;
