// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error-message': string
  input: string
  'input-container': string
  'login-container': string
}
export const cssExports: CssExports
export default cssExports
