// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom-container': string;
  'connection-container': string;
  'connections-container': string;
  'control': string;
  'deprecated-overlay': string;
  'error': string;
  'input': string;
  'node': string;
  'node-depricated': string;
  'node-id': string;
  'node-locked': string;
  'node-title': string;
  'nodeGenesis': string;
  'out': string;
  'output': string;
  'selected': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
