// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal': string;
  'modal-action-strip': string;
  'modal-bg': string;
  'modal-main-div': string;
  'modal-panel': string;
  'modal-panel-content': string;
  'modal-title': string;
  'vertical': string;
}
export const cssExports: CssExports;
export default cssExports;
