// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delete-btn': string;
  'delete-modal': string;
  'error-message': string;
  'input': string;
  'input-container': string;
  'login-container': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
