const plugins = {}
import {default as plugin9} from '@magickml/plugin-discord-client';
plugins['@magickml/plugin-discord-client'] = plugin9;
import {default as plugin10} from '@magickml/plugin-twitter-client';
plugins['@magickml/plugin-twitter-client'] = plugin10;
import {default as plugin11} from '@magickml/plugin-rest-client';
plugins['@magickml/plugin-rest-client'] = plugin11;
import {default as plugin12} from '@magickml/plugin-loop-client';
plugins['@magickml/plugin-loop-client'] = plugin12;
import {default as plugin13} from '@magickml/plugin-finetune-client';
plugins['@magickml/plugin-finetune-client'] = plugin13;
import {default as plugin14} from '@magickml/plugin-openai-client';
plugins['@magickml/plugin-openai-client'] = plugin14;
import {default as plugin15} from '@magickml/plugin-banana-client';
plugins['@magickml/plugin-banana-client'] = plugin15;
import {default as plugin16} from '@magickml/plugin-ethereum-client';
plugins['@magickml/plugin-ethereum-client'] = plugin16;
import {default as plugin17} from '@magickml/plugin-search-client';
plugins['@magickml/plugin-search-client'] = plugin17;
export default plugins;