// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'account': string;
  'add': string;
  'ankh': string;
  'bird': string;
  'close': string;
  'cloth': string;
  'cup': string;
  'feathers': string;
  'fewshot': string;
  'folder': string;
  'hand': string;
  'icon': string;
  'info': string;
  'merge': string;
  'minus': string;
  'moon': string;
  'newnode': string;
  'node-lock': string;
  'pause': string;
  'person': string;
  'play': string;
  'play-print': string;
  'properties': string;
  'refresh': string;
  'search': string;
  'seive': string;
  'snake': string;
  'state': string;
  'state-read': string;
  'state-write': string;
  'stop': string;
  'stop-sign': string;
  'switch': string;
  'temperature': string;
  'text': string;
  'tiles': string;
  'time': string;
  'trash': string;
  'warn': string;
  'water': string;
  'water-play': string;
  'water-run': string;
}
export const cssExports: CssExports;
export default cssExports;
