FROM magickml/magick:latest

COPY . /app
WORKDIR /app

RUN poetry install --no-interaction --no-ansi -vvv
# RUN poetry install --no-root

RUN npm install

RUN npm run build-cloud-agent-worker

ENTRYPOINT [ "npm", "run" ]
CMD [ "start-cloud-agent-worker" ]