FROM debian:bookworm-slim

RUN apt update && apt install -y python3.11 python3-pip python3-virtualenv python3-poetry nodejs npm
RUN poetry config installer.max-workers 10

# Optionally, globally configure npm or poetry here if there are any global settings you'd like to apply

# skip NX cache builds
env NX_SKIP_NX_CACHE=true

# Clean up the apt cache to reduce the image size
RUN apt-get clean && rm -rf /var/lib/apt/lists/*