// This file is automatically generated.
// Please do not change this file!
// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface CssExports {

}
export const cssExports: CssExports;
export default cssExports;
