export declare const latitudeApiRootUrl: string;
export declare const thothApiRootUrl: string;
export declare const oAuthClientId: string | undefined;
export declare const appRootUrl: string | undefined;
export declare const useLatitude: boolean;
export declare const sharedb: boolean;
export declare const websockets: boolean;
export declare const feathers: boolean;
export declare const feathersUrl = "http://localhost:3030";
export declare const websocketUrl = "ws://localhost:8080";
