import { LLMModels, LLMProviders } from './types'

export const modelMap: Record<LLMModels, LLMProviders> = {
  [LLMModels.GPT35Turbo]: LLMProviders.OpenAI,
  [LLMModels.GPT3]: LLMProviders.OpenAI,
  [LLMModels.Davinci]: LLMProviders.OpenAI,
  [LLMModels.Curie]: LLMProviders.OpenAI,
  [LLMModels.Babbage]: LLMProviders.OpenAI,
  [LLMModels.Ada]: LLMProviders.OpenAI,
  [LLMModels.GeminiPro]: LLMProviders.Unknown,
  [LLMModels.Palm]: LLMProviders.Unknown,
  [LLMModels.Mistral]: LLMProviders.Unknown,
  [LLMModels.Anthropic]: LLMProviders.Unknown,
  [LLMModels.Sagemaker]: LLMProviders.Unknown,
  [LLMModels.Bedrock]: LLMProviders.Unknown,
  [LLMModels.Anyscale]: LLMProviders.Unknown,
  [LLMModels.PerplexityAI]: LLMProviders.Unknown,
  [LLMModels.VLLM]: LLMProviders.Unknown,
  [LLMModels.DeepInfra]: LLMProviders.Unknown,
  [LLMModels.J2Light]: LLMProviders.Unknown,
  [LLMModels.J2Mid]: LLMProviders.Unknown,
  [LLMModels.J2Ultra]: LLMProviders.Unknown,
  [LLMModels.NLPCloud]: LLMProviders.Unknown,
  [LLMModels.Replicate]: LLMProviders.Unknown,
  [LLMModels.Cohere]: LLMProviders.Unknown,
  [LLMModels.TogetherAI]: LLMProviders.Unknown,
  [LLMModels.AlephAlpha]: LLMProviders.Unknown,
  [LLMModels.Baseten]: LLMProviders.Unknown,
  [LLMModels.OpenRouter]: LLMProviders.Unknown,
  [LLMModels.CustomAPI]: LLMProviders.Unknown,
  [LLMModels.Petals]: LLMProviders.Unknown,
}
