export enum IndirectDataType {
  YOUTUBE_VIDEO = 'youtube_video',
  PDF_FILE = 'pdf_file',
  WEB_PAGE = 'web_page',
  SITEMAP = 'sitemap',
  XML = 'xml',
  DOCX = 'docx',
  DOCS_SITE = 'docs_site',
  NOTION = 'notion',
  CSV = 'csv',
  MDX = 'mdx',
  IMAGE = 'image',
  UNSTRUCTURED = 'unstructured',
  JSON = 'json',
  OPENAPI = 'openapi',
  GMAIL = 'gmail',
  SUBSTACK = 'substack',
  YOUTUBE_CHANNEL = 'youtube_channel',
  DISCORD = 'discord',
  CUSTOM = 'custom',
  RSSFEED = 'rss_feed',
  BEEHIIV = 'beehiiv',
  GOOGLE_DRIVE = 'google_drive',
  DIRECTORY = 'directory',
  SLACK = 'slack',
  DROPBOX = 'dropbox',
  TEXT_FILE = 'text_file',
}

export enum SpecialDataType {
  AUTO = 'auto',
  QNA_PAIR = 'qna_pair',
}

export enum DataType {
  AUTO = SpecialDataType.AUTO,
  TEXT = 'text', // Replace "text" with the actual value from DirectDataType.TEXT.value
  YOUTUBE_VIDEO = IndirectDataType.YOUTUBE_VIDEO,
  PDF_FILE = IndirectDataType.PDF_FILE,
  WEB_PAGE = IndirectDataType.WEB_PAGE,
  SITEMAP = IndirectDataType.SITEMAP,
  XML = IndirectDataType.XML,
  DOCX = IndirectDataType.DOCX,
  // DOCS_SITE = IndirectDataType.DOCS_SITE,
  // NOTION = IndirectDataType.NOTION,
  CSV = IndirectDataType.CSV,
  MDX = IndirectDataType.MDX,
  // QNA_PAIR = SpecialDataType.QNA_PAIR,
  IMAGE = IndirectDataType.IMAGE,
  // UNSTRUCTURED = IndirectDataType.UNSTRUCTURED,
  JSON = IndirectDataType.JSON,
  OPENAPI = IndirectDataType.OPENAPI,
  // GMAIL = IndirectDataType.GMAIL,
  SUBSTACK = IndirectDataType.SUBSTACK,
  YOUTUBE_CHANNEL = IndirectDataType.YOUTUBE_CHANNEL,
  DISCORD = IndirectDataType.DISCORD,
  // CUSTOM = IndirectDataType.CUSTOM,
  RSSFEED = IndirectDataType.RSSFEED,
  // BEEHIIV = IndirectDataType.BEEHIIV,
  // GOOGLE_DRIVE = IndirectDataType.GOOGLE_DRIVE,
  // DIRECTORY = IndirectDataType.DIRECTORY,
  // SLACK = IndirectDataType.SLACK,
  // DROPBOX = IndirectDataType.DROPBOX,
  TEXT_FILE = IndirectDataType.TEXT_FILE,
}
