// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deploy-shield': string;
  'deploy-window': string;
  'editor-container': string;
  'editor-deployments-wrapper': string;
  'editor-toolbar': string;
  'folder-arrow': string;
  'inactive': string;
  'list-item': string;
  'load-button': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
