const plugins = {}
import {default as plugin0} from '@magickml/plugin-discord-server';
plugins['@magickml/plugin-discord-server'] = plugin0;
import {default as plugin1} from '@magickml/plugin-twitter-server';
plugins['@magickml/plugin-twitter-server'] = plugin1;
import {default as plugin2} from '@magickml/plugin-rest-server';
plugins['@magickml/plugin-rest-server'] = plugin2;
import {default as plugin3} from '@magickml/plugin-loop-server';
plugins['@magickml/plugin-loop-server'] = plugin3;
import {default as plugin4} from '@magickml/plugin-task-server';
plugins['@magickml/plugin-task-server'] = plugin4;
import {default as plugin5} from '@magickml/plugin-googleai-server';
plugins['@magickml/plugin-googleai-server'] = plugin5;
import {default as plugin6} from '@magickml/plugin-openai-server';
plugins['@magickml/plugin-openai-server'] = plugin6;
import {default as plugin7} from '@magickml/plugin-search-server';
plugins['@magickml/plugin-search-server'] = plugin7;
import {default as plugin8} from '@magickml/plugin-bluesky-server';
plugins['@magickml/plugin-bluesky-server'] = plugin8;
import {default as plugin9} from '@magickml/plugin-qa-server';
plugins['@magickml/plugin-qa-server'] = plugin9;
import {default as plugin10} from '@magickml/plugin-elevenlabs-server';
plugins['@magickml/plugin-elevenlabs-server'] = plugin10;
import {default as plugin11} from '@magickml/plugin-database-server';
plugins['@magickml/plugin-database-server'] = plugin11;
export default plugins;