const plugins = {}
import {default as plugin0} from '@magickml/plugin-github-server';
plugins['@magickml/plugin-github-server'] = plugin0;
import {default as plugin1} from '@magickml/plugin-rest-server';
plugins['@magickml/plugin-rest-server'] = plugin1;
import {default as plugin2} from '@magickml/plugin-discord-server';
plugins['@magickml/plugin-discord-server'] = plugin2;
import {default as plugin3} from '@magickml/plugin-twitter-server';
plugins['@magickml/plugin-twitter-server'] = plugin3;
import {default as plugin4} from '@magickml/plugin-loop-server';
plugins['@magickml/plugin-loop-server'] = plugin4;
import {default as plugin5} from '@magickml/plugin-task-server';
plugins['@magickml/plugin-task-server'] = plugin5;
import {default as plugin6} from '@magickml/plugin-googleai-server';
plugins['@magickml/plugin-googleai-server'] = plugin6;
import {default as plugin7} from '@magickml/plugin-openai-server';
plugins['@magickml/plugin-openai-server'] = plugin7;
import {default as plugin8} from '@magickml/plugin-search-server';
plugins['@magickml/plugin-search-server'] = plugin8;
import {default as plugin9} from '@magickml/plugin-bluesky-server';
plugins['@magickml/plugin-bluesky-server'] = plugin9;
import {default as plugin10} from '@magickml/plugin-elevenlabs-server';
plugins['@magickml/plugin-elevenlabs-server'] = plugin10;
import {default as plugin11} from '@magickml/plugin-database-server';
plugins['@magickml/plugin-database-server'] = plugin11;
import {default as plugin12} from '@magickml/plugin-anthropic-server';
plugins['@magickml/plugin-anthropic-server'] = plugin12;
import {default as plugin13} from '@magickml/plugin-intent-server';
plugins['@magickml/plugin-intent-server'] = plugin13;
import {default as plugin14} from '@magickml/plugin-storage-server';
plugins['@magickml/plugin-storage-server'] = plugin14;
import {default as plugin15} from '@magickml/plugin-cog-server';
plugins['@magickml/plugin-cog-server'] = plugin15;
import {default as plugin16} from '@magickml/plugin-weather-server';
plugins['@magickml/plugin-weather-server'] = plugin16;
export default plugins;