name: Electron Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [19.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npx
        run: npm install -g npx --force
      - name: Install Capacitor
        run: npm install -g @capacitor/cli --force
      - name: npm Install Dependencies
        run: npm install && npm i vite
      - name: Install Dependencies
        run: npm ci 
      - name: Clean Output Folder
        run: rm -rf apps/client/electron/output
      - name: Install cross-env
        run: npm install -g cross-env
      - name: Set NODE_ENV to production
        run: cross-env NODE_ENV=production
      - name: Add Electron Platform to Capacitor
        run: cd apps/client && npx cap add electron
      - name: Copy Web Assets to Electron
        run: cd apps/client && npx cap copy electron
      - name: Open Electron
        run: cd apps/client && npx cap open electron
      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-${{ matrix.os }}
          path: ./apps/client/electron/output
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Attach Artifact
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./apps/client/electron/output
          asset_name: magick-electron-${{ matrix.os }}-${{ github.ref }}
          asset_content_type: application/zip
      - name: Upload Source Maps
        uses: honeybadger-io/github-upload-sourcemap-action@master
        with:
          working_directory: ./apps/client/electron/output
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
