name: Magick ESLint Check

on: [push, pull_request]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Node.js
        uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954 # v2.4.0
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
