name: Magick ESLint Check

on: [push, pull_request]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint